#!/bin/bash
# Author : Gabriel Lucas
# Copy .h header files and binaries from a project named located in SOURCE_PATH into an archive
# Usage : create-tar SOURCE_PATH

if [ -z "$1" ]
then
	echo "No source path supplied"
	exit
fi

directories="bin lib script robot-robot robot-comlib"

mkdir bin
mkdir lib
mkdir script

############ robot-robot ############

robot_name="robot-robot"
robot_source="$1/$robot_name"
robot_binary="$robot_source/lib$robot_name.so"

source=($(find $robot_source -name '*.h' -print))

dest=($(find $robot_source -name '*.h' -print | sed "s/.*\($robot_name\)/\1/g"  ))

for ((i=0; i<${#source[@]}; i++)); do
	mkdir -p "${dest[i]}" && cp "${source[i]}" "${dest[i]}"
done

cp $robot_binary lib

############ robot-comlib ############

robot_name="robot-comlib"
robot_source="$1/$robot_name/src"
robot_binary="$1/$robot_name/lib$robot_name.so"

source=($(find $robot_source -name '*.h' -print))

dest=($(find $robot_source -name '*.h' -print | sed "s/.*\(src\)/\1/g" |  sed "s/src/$robot_name/g" ))

for ((i=0; i<${#source[@]}; i++)); do
	mkdir -p "${dest[i]}" && cp "${source[i]}" "${dest[i]}"
done

rm -r robot-comlib/Examples

cp $robot_binary lib

############ robot-daemon ############

robot_name="robot-daemon"
robot_path="$1/$robot_name"

cp "$robot_path/get_TTYbyUSBid.sh" script
cp "$robot_path/$robot_name" bin

############ robot-utility ############

robot_name="robot-utility"
robot_path="$1/$robot_name"

cp "$robot_path/get_USBidbyTTY.sh" script
cp "$robot_path/robot" bin

tar -cf robot-libraries-package.tar $directories
rm -r $directories


